#! /usr/bin/env python

"""Utility module for administrative tasks.

A python script version of Django's command-line utility for
administrative tasks (``django-admin``). Additionally, puts the project
package on ``sys.path`` and defines the ``DJANGO_SETTINGS_MODULE``
variable to point to the jwql ``settings.py`` file.

Generated by ``django-admin startproject`` using Django 2.0.1.

Use
---

    To run the web app server:
    ::

        python manage.py runserver

    To start the interactive shell:
    ::

        python manage.py shell

    To run tests for all installed apps:
    ::

        python manage.py test

References
----------
For more information please see:
    ``https://docs.djangoproject.com/en/2.0/ref/django-admin/``
"""

import os
import sys
import pathlib
import shutil

# --- Ensure 'jwql' is always importable by manipulating sys.path ---
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
# Also ensure parent of jwql/ is in sys.path
PARENT_DIR = os.path.abspath(os.path.join(PROJECT_ROOT, os.pardir))
if PARENT_DIR not in sys.path:
    sys.path.insert(0, PARENT_DIR)

# Try importing jwql, fail with clear message if not found
try:
    import jwql  # noqa: F401
except ImportError:
    sys.stderr.write("Could not import 'jwql'. Ensure the jwql directory contains an __init__.py file and is in the project root.\n")
    sys.exit(1)

from jwql.utils import get_config

def ensure_idempotent_symlink(target_path: pathlib.Path, symlink_path: pathlib.Path):
    """
    PUBLIC_INTERFACE
    Ensure that a symlink at symlink_path points to target_path,
    handling all edge cases:
     - If symlink exists and points correctly: do nothing.
     - If symlink exists and is broken/points elsewhere: remove and make new.
     - If a file or dir exists: safely remove before creating the symlink.
     - If nothing exists: ensure parent exists, then create symlink.

    Args:
        target_path (Path): The target to symlink to.
        symlink_path (Path): The symlink path to create.
    """
    # Absolute resolution
    target_path_abs = target_path.resolve()
    # covers both valid and broken symlinks
    if symlink_path.exists() or symlink_path.is_symlink():
        if symlink_path.is_symlink():
            try:
                cur_target = symlink_path.resolve(strict=True)
                if cur_target == target_path_abs:
                    return
                # Symlink points elsewhere, remove it
                symlink_path.unlink()
            except FileNotFoundError:
                # Broken symlink, remove it
                symlink_path.unlink()
        elif symlink_path.is_dir():
            shutil.rmtree(symlink_path)
        else:
            symlink_path.unlink()
    # Make dirs for parent if needed
    symlink_path.parent.mkdir(parents=True, exist_ok=True)
    symlink_path.symlink_to(target_path_abs, target_is_directory=True)

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "jwql_proj.settings")

    directory_mapping = {
        'filesystem': 'filesystem',
        'outputs': 'outputs',
        'preview_image_filesystem': 'preview_images',
        'thumbnail_filesystem': 'thumbnails'
    }

    # PUBLIC_INTERFACE
    # Fully idempotent symlink setup for Django static/data handling
    config = get_config()
    for directory in ['filesystem', 'outputs', 'preview_image_filesystem', 'thumbnail_filesystem']:
        symlink_location = os.path.join(os.path.dirname(__file__), 'apps', 'jwql', 'static', directory_mapping[directory])
        symlink_location_path = pathlib.Path(symlink_location)
        symlink_target = config[directory]
        symlink_target_path = pathlib.Path(symlink_target)
        ensure_idempotent_symlink(symlink_target_path, symlink_location_path)

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    # Default to 0.0.0.0:3001 if not specified and running runserver
    if (
        len(sys.argv) >= 2
        and sys.argv[1] == "runserver"
        and all(":" not in arg for arg in sys.argv[2:])
    ):
        sys.argv.append("0.0.0.0:3001")

    execute_from_command_line(sys.argv)

